### ISSUE TITLE
openSUSE: edit button causes segfault

### ISSUE THREAD

**Issue by DAP-DarkneSS** [loast/krudio#11]
![opensuse-krudio-segfault](https://cloud.githubusercontent.com/assets/940114/17107223/0ae8facc-5297-11e6-839b-8b00df318dec.png)
openSUSE 13.2 x64, Qt 5.7.0
PS Russian is fine too.

(gdb) bt full
#0  Krudio::on_editStation_released (this=0x7fffffffdc00) at krudio.cpp:678

No locals.
#1  0x0000000000415295 in Krudio::qt_static_metacall (_o=0x668c00, _o@entry=0x7fffffffdc00, _c=4294954144,

```
_c@entry=QMetaObject::InvokeMetaMethod, _id=-1, _id@entry=24, _a=0x7fffffffcc80, _a@entry=0x7fffffffce20)
at moc_krudio.cpp:202
```

No locals.
#2  0x0000000000415603 in Krudio::qt_metacall (this=0x7fffffffdc00, _c=QMetaObject::InvokeMetaMethod, _id=24,

```
_a=0x7fffffffce20) at moc_krudio.cpp:236
```

No locals.
#3  0x00007ffff64bfd9c in QMetaObject::activate(QObject_, int, int, void_*) () from /usr/lib64/libQt5Core.so.5

No symbol table info available.
#4  0x00007ffff74c410d in ?? () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#5  0x00007ffff74c5483 in ?? () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#6  0x00007ffff74c5614 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#7  0x00007ffff742846a in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#8  0x00007ffff73e4b6c in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#9  0x00007ffff73ec4cb in QApplication::notify(QObject_, QEvent_) () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#10 0x00007ffff6497795 in QCoreApplication::notifyInternal2(QObject_, QEvent_) () from /usr/lib64/libQt5Core.so.5

No symbol table info available.
#11 0x00007ffff73eaf53 in QApplicationPrivate::sendMouseEvent(QWidget_, QMouseEvent_, QWidget_, QWidget_, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#12 0x00007ffff7441369 in ?? () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#13 0x00007ffff74437a3 in ?? () from /usr/lib64/libQt5Widgets.so.5

---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#14 0x00007ffff73e4b6c in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#15 0x00007ffff73ebaf0 in QApplication::notify(QObject_, QEvent_) () from /usr/lib64/libQt5Widgets.so.5

No symbol table info available.
#16 0x00007ffff6497795 in QCoreApplication::notifyInternal2(QObject_, QEvent_) () from /usr/lib64/libQt5Core.so.5

No symbol table info available.
#17 0x00007ffff6c300bb in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()

   from /usr/lib64/libQt5Gui.so.5
No symbol table info available.
#18 0x00007ffff6c31c15 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib64/libQt5Gui.so.5

No symbol table info available.
#19 0x00007ffff6c13cdb in QWindowSystemInterface::sendWindowSystemEvents(QFlagsQEventLoop::ProcessEventsFlag) ()

   from /usr/lib64/libQt5Gui.so.5
No symbol table info available.
#20 0x00007fffefcfcde0 in ?? () from /usr/lib64/libQt5XcbQpa.so.5

No symbol table info available.
#21 0x00000030c3c4ba04 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0

No symbol table info available.
#22 0x00000030c3c4bc48 in ?? () from /usr/lib64/libglib-2.0.so.0

No symbol table info available.
#23 0x00000030c3c4bcec in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0

No symbol table info available.
#24 0x00007ffff64e602c in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) ()

   from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#25 0x00007ffff6495a6b in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib64/libQt5Core.so.5

No symbol table info available.
#26 0x00007ffff649d866 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5

No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#27 0x0000000000407ab2 in main (argc=1, argv=0x7fffffffdd38) at main.cpp:21

```
    a = <incomplete type>
    w = {<QMainWindow> = {<No data fields>}, static staticMetaObject = {d = {
          superdata = 0x7ffff7aa8160 <QMainWindow::staticMetaObject>, 
          stringdata = 0x4164c0 <qt_meta_stringdata_Krudio>, data = 0x416160 <qt_meta_data_Krudio>, 
          static_metacall = 0x415250 <Krudio::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
          relatedMetaObjects = 0x0, extradata = 0x0}}, ceckBUFFtimer = 0x6884b0, ui = 0x6711a0}
```

(gdb) quit

**Comment by DAP-DarkneSS** [comment]
Btw
openSUSE package: https://software.opensuse.org/download.html?project=home%3ADarkSS&package=krudio
Ubuntu package: https://software.opensuse.org/download.html?project=home%3ADarkSS%3Adeb&package=krudio

**Comment by alexyalinc** [comment]
Ok. I fix this is next time. Thanks for the packages for ubuntu and openSUSE. I'll add them in the readme.
